### ISSUE TITLE
Добавление валюты в БД

### ISSUE THREAD

**Issue by PrinceGallywix** [JobExplores/Competencer#40]
Прошу:
- Добавить поле текстовое ''currency" в таблицу salaries
- Добавить парсинг валюты в парсере БД
- Обновить схему
- Обновить mock

**Comment by PrinceGallywix** [comment]
Также, необходимо добавить туда же булево поле "gross", которое принимает истинное значение, если зп указана до вычета налогов и ложное, если зп указана "на руки"

**Comment by sergeyomel** [comment]
https://github.com/JobExplores/Competencer/pull/49
